DROP TABLE IF EXISTS BOOKS, USERS, REVIEWS;

CREATE TABLE BOOKS(
    isbn  VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    author VARCHAR NOT NULL,
    year VARCHAR NOT NULL
    );
   
 
CREATE TABLE USERS(
    id SERIAL PRIMARY KEY,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL
    );
   

CREATE TABLE REVIEWS(
    id SERIAL PRIMARY KEY,
    book  VARCHAR REFERENCES BOOKS (isbn),
    rating INTEGER NOT NULL,
    review VARCHAR NOT NULL
    );